### ISSUE TITLE
 The variables "aks_podSubnet", "aks_podsubnet" differ only in casing

### ISSUE THREAD

**Issue by luticm** [Azure/Medical-Claims-Transaction-Processing-at-scale#14]
\infrastructure\AKS-Construction\bicep\network.bicep(173,5) : Error BCP353: The variables "aks_podSubnet", "aks_podsubnet" differ only in casing. The ARM deployments engine is not case sensitive and will not be able to distinguish between them.
: Error BCP353: The variables "aks_podSubnet", "aks_podsubnet" differ only in casing. The ARM deployments engine is not case sensitive and will not be able to distinguish between them.
\AKS-Construction\bicep\network.bicep(409,9) : Warning BCP334: The provided value can have a length as small as 0 and may be too short to assign to a target with a configured minimum length of 3.
\main.bicep(94,12) : Error BCP104: The referenced module has errors.
\AKS-Construction\bicep\main.bicep(130,16) : Error BCP104: The referenced module has errors.

Exception reported when upgraded AZ BICEP. 
Version: Bicep CLI version 0.21.1 (d4acbd2a9f)

**Comment by fonsecamar** [comment]
@luticm , fixed on PR #30
