### ISSUE TITLE
Recommendation Intermittently Returns Input JSON

### ISSUE THREAD

**Issue by timwferro** [Azure/Medical-Claims-Transaction-Processing-at-scale#21]
When using the "Ask for Recommendation" button on a claim, it intermittently returns the full input JSON along with the response.

![image](https://github.com/Azure/Medical-Claims-Transaction-Processing-at-scale/assets/44404513/64ebbec7-f966-447c-af7b-34074e9551a3)

**Comment by joelhulen** [comment]
I just submitted a PR that should fix this. Feel free to reopen if it doesn't work for you.
