### ISSUE TITLE
ACA deployment error with existing OpenAI models

### ISSUE THREAD

**Issue by luticm** [Azure/Medical-Claims-Transaction-Processing-at-scale#22]
New ACA deployment with existing OpenAI models generate error when trying to find resource under Claims resource group (and not the one specified in openAiRg).

> ./deploy/powershell/Unified-Deploy.ps1 -resourceGroup 'Claimsv3' -subscription SubId -location 'East US' -openAiRg 'cosmicgbb-ai' -openAiName 'cosmicgbb-openai' -openAiCompletionsDeployment 'completions'

ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/SubId/resourceGroups/Claimsv1/providers/Microsoft.Resources/deployments/acamain","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceNotFound","message":"The Resource 'Microsoft.CognitiveServices/accounts/cosmicgbb-openai' under resource group 'Claimsv1' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"},{"code":"ResourceNotFound","message":"The Resource 'Microsoft.CognitiveServices/accounts/cosmicgbb-openai' under resource group 'Claimsv1' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}]}}

**Comment by hatboyzero** [comment]
Please try the branch `mg-22-openai-rg-fix` referenced in pull request 23 linked above and see if that resolves the issue.

**Comment by luticm** [comment]
Thank you for fixing the parameter issue @hatboyzero.
New deployment shows the following error, but all other resources seems to be created.

App Insights Instrumentation Key:
ERROR: argument --name/-n: expected one argument

**Comment by hatboyzero** [comment]
That might be an artifact of recent refactors to the deployment scripts to support ACA and AKS.  Can you upload the output log (minus any sensitive values like API keys and the like)?

**Comment by luticm** [comment]
Sent directly to your inbox.

**Comment by joelhulen** [comment]
@luticm and @hatboyzero is this issue resolved?

**Comment by hatboyzero** [comment]
Yes.

**Comment by joelhulen** [comment]
@luticm can you please close this issue?

**Comment by fonsecamar** [comment]
@luticm , fixed on PR #30
